version: '3'

services:
  app:
    container_name: nft-maker
    image: golang:1.17-alpine3.15
    networks:
      - private
    volumes:
      - ./:/go/app
      - app-pkg:/go/pkg/mod
    working_dir: /go/app
    command: go run cmd/main.go
    depends_on:
      - database
    restart: always

  database:
    container_name: mariadb
    image: mariadb:10.6.5-focal
    environment:
      - MYSQL_ROOT_PASSWORD=example
    networks:
      private:
        aliases:
          - db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - app-db:/var/lib/mysql
    restart: always

  db_admin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.1
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=example
    ports:
      - 2000:80
    networks:
      - private
    depends_on:
      - database
    restart: always
    
    

  # db_admin:
  #   container_name: phpmyadmin
  #   # image: phpmyadmin:5.1.1-fpm-alpine
  #   image: phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #   ports:
  #     - 6000:80
  #   networks:
  #     - private
  #   depends_on:
  #     - database
  #   restart: always

networks:
  private:
    driver: bridge

volumes:
  app-pkg:
  app-db: