version: '3'

services:
  app:
    container_name: nft-maker
    image: golang:1.17-alpine3.15
    environment:
      - TZ=Africa/Johannesburg
    networks:
      private:
        aliases:
          - nft-maker-app
    volumes:
      - ./:/go/app
      - app-pkg:/go/pkg/mod
    working_dir: /go/app
    command: go run cmd/main.go
    depends_on:
      - database
    restart: always

  database:
    container_name: mariadb
    image: mariadb:10.6.5-focal
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - TZ=Africa/Johannesburg
    networks:
      private:
        aliases:
          - nft-maker-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - app-db:/var/lib/mysql
    restart: always

  db_admin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.1
    environment:
      - PMA_HOST=nft-maker-db
      - PMA_USER=root
      - PMA_PASSWORD=example
      - TZ=Africa/Johannesburg
    networks:
      - private
    depends_on:
      - database
    restart: always

  # HAProxy
  proxy:
    container_name: haproxy
    image: haproxy:2.5-alpine3.15
    environment:
      - TZ=Africa/Johannesburg
    ports:
      - "5000:8080"
    networks:
      - public
      - private
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    restart: always
    

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  app-pkg:
  app-db: